### ISSUE TITLE
FYI - ipaddr-py exists for the same reason

### ISSUE THREAD

**Issue by gpshead** [phihag/ipaddress#23]
https://github.com/google/ipaddr-py (formerly http://code.google.com/p/ipaddr-py/) has existed for a while...

**Comment by phihag** [comment]
Thank you, I am fully aware of it, having [contributed to ipaddr](https://github.com/google/ipaddr-py/commit/20bf7c356bd6d0d4c13570cd63ec4d04460a5a03) [myself](https://github.com/google/ipaddr-py/commit/ebc24565854e22be8d19c51940367c1902f92191).


So here goes my short summary of the history of both. ipaddr was originally developed as an in-house google library, and then open-sourced (in these days, you had to jump through a lot of google-specific hoops). It was then [suggested](http://bugs.python.org/issue3959) to include ipaddr in the Python standard library. [There was quite a lot of discussion at the time](https://lwn.net/Articles/337684/), with multiple projects being suggested for stdlib inclusion.

Eventually, things settled with Python 3.3, the first version of Python to include the [ipadress](http://docs.python.org/dev/library/ipaddress) module. Both modules have different function and class names as well as slightly different semantics. See [PEP 3144](https://www.python.org/dev/peps/pep-3144/) for more details.

As it was always planned, inclusion of the library into the Python stdlib meant that ipaddr was on its way  out. While there were some patches and a PyPi release, development of ipaddr has now been dead for close to a year (look at the [history](https://github.com/google/ipaddr-py/commits/master) - after 2012 there is effectively no more development. In contrast, although it has matured, development on ipaddress is still [very much alive](https://hg.python.org/cpython/log/b2a1fe8f1b11/Lib/ipaddress.py).
As it was always planned, inclusion of the library into the Python stdlib meant that ipaddr was on its way  out. While there were some patches and a PyPi release, development of ipaddr has now been dead for close to a year (look at the [history](https://github.com/google/ipaddr-py/commits/master) - after 2012 there is effectively no more development. In contrast, although it has matured, development on ipaddress is still [very much alive](https://hg.python.org/cpython/log/b2a1fe8f1b11/Lib/ipaddress.py).

This project backports the ipaddress module to Python 2.6, 2.7, and 3.2. This allows developers to let their code run on older Python versions that are still the only option on many old but stable systems (namely RHEL).

Being a module in the standard library, ipaddress is very much the way forward. ipaddr-py managed to some rudimentary Python 3 support toward its end, but it still *doesn't even work* on current Python versions without major modifications. The inclusion into the standard library means that ipaddress is way more popular nowadays. If you look at the [download](https://pypi.python.org/pypi/ipaddr) [numbers](https://pypi.python.org/pypi/ipaddress), you'll see that nearly 10 times as many users are using ipaddress *on Python 2.x*.

**Comment by gpshead** [comment]
cool, thanks for the history!
