### ISSUE TITLE
packed is a bytearray on some platforms and str on others

### ISSUE THREAD

**Issue by oschwald** [phihag/ipaddress#28]
See https://github.com/maxmind/GeoIP2-python/issues/41

On Ubuntu using 2.7.13, `type(ipaddress.ip_address(u'128.101.101.101').packed)` returns `<type 'str'>`, but the user in that issue is reporting receiving `<type 'bytearray'>` on macOS 10.12.2.

**Comment by phihag** [comment]
I strongly suspect the original poster is using py2-ipaddress, a backport I regard as dangerous and defective for the [reasons outlined here](https://github.com/phihag/ipaddress/blob/master/OTHER_BACKPORTS.md). I have commented in maxmind/GeoIP2-python#41 and asked for confirmation.

**Comment by oschwald** [comment]
Thanks for following up. After testing `py2-ipaddress` myself, I suspect you are right. I'll close this issue and reopen if the original reporter provides contrary evidence.
