### ISSUE TITLE
Push tags to github

### ISSUE THREAD

**Issue by ekohl** [phihag/ipaddress#29]
It would be useful if releases were tagged and pushed as tags. There's a good chance you locally already do so, but haven't pushed them since git doesn't do this by default. You can use ```git push --tags``` or if you use annotated tags [use followTags](https://stackoverflow.com/questions/3745135/push-git-commits-tags-simultaneously/3745250#3745250) to automatically include them on ```git push```.

**Comment by phihag** [comment]
Thank you for the report. Tags are [now available](https://github.com/phihag/ipaddress/tags). I'm still looking into automating the release process, and if possible signing the commits/tags.

**Comment by ekohl** [comment]
Thanks!
