### ISSUE TITLE
RPM packaging?

### ISSUE THREAD

**Issue by strizhechenko** [phihag/ipaddress#32]
Hi.

I've this backport-library as dependency in my project with python 2.6 and 2.7 support. I want to package my project in RPM to ease shipping for RHEL/CentOS 6/7 users. So, I need to duplicate dependencies in .spec. So, I need RPM version of each dependency. 

I don't want to bother you a lot with this "feature", but:
- would you like to accept a pull request if I'll will do all the packaging routine?
- Or maybe you already planned to do it? 
- And I also don't know who should be a maintainer of packaged PRM (I want to submit it to epel or somewhere else).

What do you think? (Sorry for poor english).

**Comment by phihag** [comment]
Coming from debian, my understanding is that normally the package specification is an individual repository. But if any changes are necessary, feel free to suggest them!

I have no plans to package this project for RPM, and don't use any RPM-based distribution regularly, so I am not available as a maintainer.

I'm closing this issue now, but feel free to post any further questions you may have.
