### ISSUE TITLE
Context Manager

### ISSUE THREAD

**Issue by scivision** [phihag/ipaddress#33]
This issue opened in error, my apologies

**Comment by phihag** [comment]
I apologize, but I'm not sure how you'd use any ipaddress object as a context manager.
A cursory search for `__enter__` in the [upstream source code](https://github.com/python/cpython/blob/91dc64ba3f51100540b2ab6c6cd72c3bb18a6d49/Lib/ipaddress.py) did not turn up anything as well.

Can you post example code that fails with this port, but works with the stdlib ipaddress?

**Comment by scivision** [comment]
This issue opened in error, my apologies
