### ISSUE TITLE
buildout legacy distribution

### ISSUE THREAD

**Issue by papachoco** [phihag/ipaddress#40]
I am getting an error while getting distribution for 'ipaddress==1.0.22' using buildout which is not using wheel, but legacy source. The distribution for version 1.0.21 indeed can be found using buildout.  Is this a case of a caching issue w/ pypi? I noticed the setup.py in the master branch still points to 1.0.21

Carlos

**Comment by phihag** [comment]
I apologize. In response to #39 I added a release script and used it to release 1.0.22, but I forgot to include a line to push to master.

GitHub master is now 1.0.22. This should fix your problem. If it does not, please post here. Thank you for the report!

**Comment by phihag** [comment]
Can you post a link to the site where you see these details? I can see the source distribution just fine at https://pypi.python.org/packages/97/8d/77b8cedcfbf93676148518036c6b1ce7f8e14bf07e95d7fd4ddcb8cc052f/ipaddress-1.0.22.tar.gz#md5=74c1ce3109f30eaa1ab3dd342e7b76d4 . Is there any other legacy distribution I'm missing?

**Comment by papachoco** [comment]
Indeed ... but b/c the tar file was loaded after the wheel file, legacy installations cannot get the distribution.

**Comment by phihag** [comment]
The tar file was loaded *before* the wheel file:

    add source file ipaddress-1.0.22.tar.gz	2018-04-15 18:00:47.003 phihag
    add 2.7 file ipaddress-1.0.22-py2.py3-none-any.whl	2018-04-15 18:00:48.995 phihag

**Comment by phihag** [comment]
On further investigation and looking into the buildout source code, the problem seems to be pypi-related: the 1.0.22 release does not show up at https://pypi.org/simple/ipaddress/ .

**Comment by phihag** [comment]
Filed as pypa/pypi-legacy#796 .

**Comment by phihag** [comment]
As mentioned in https://github.com/pypa/warehouse/issues/3694#issuecomment-381555918 , this was a pypi issue and has been fixed by the pypi team.
