### ISSUE TITLE
Why this is only for python 3.3+

### ISSUE THREAD

**Issue by Assassinkin** [phihag/ipaddress#41]
why this is just for python 3.3+ ? I installed it on python 3.6 and it seems to work fine?

**Comment by phihag** [comment]
This project is a [backport](https://en.wikipedia.org/wiki/Backporting) of the [ipaddress package in the Python standard library](https://docs.python.org/3/library/ipaddress.html), aimed at Python 2.6, Python 2.7, and Python 3.2. Basically, I took the code from the Python 3.3+ ipaddress package and adapted it to older versions of Python.

If you have Python 3.3 or newer (for instance, Python 3.6), ipaddress is already available in the standard library and there is no point in installing this backport.

I don't actively break support for 3.6 and the like, but the version in the standard library will work at least as good as this backport. By the way, `3.3+` means 3.3 or any newer version, e.g. 3.4, 3.5, 3.6, 4.0.

**Comment by Assassinkin** [comment]
@phihag  Thanks for the clarification.
