### ISSUE TITLE
ipaddres in requirements.txt is incorrectly linked to another project

### ISSUE THREAD

**Issue by roniemartinez** [phihag/ipaddress#50]
Hi,

NOTE: This is not a bug in ipaddress, documenting here for future reference

I recently encountered incorrect Github linking of this project to https://github.com/HaDiNet/python-ipaddress

![image](https://user-images.githubusercontent.com/2573537/59167567-65a7d880-8b64-11e9-831e-1c31186d807a.png)

I already reported the issue to Github since I think the wrong project is taking all the credits this project deserves.

![image](https://user-images.githubusercontent.com/2573537/59167564-5e80ca80-8b64-11e9-8cae-886efef215d6.png)

Thank you.

**Comment by roniemartinez** [comment]
Hello,

The response from Github was immediate :)

> Hi Ronie,
> 
> Thanks for contacting GitHub Support!
> 
> I've taken a look, and you're quite right. It looks like our algorithms got it wrong on this occasion.
> 
> I've reassigned the ipaddress package to phihag/ipaddress just now, so the trouble should be resolved.
> 
> Let us know if there's anything else we can do!


Now this repo got the number of dependent packages it deserves:
![image](https://user-images.githubusercontent.com/2573537/59175180-23dc5980-8b87-11e9-94ae-d276016b9448.png)

Cheers!

**Comment by phihag** [comment]
Thank you very much!
